version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: invoice_matcher_mongo
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: