# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import matcher_pb2 as matcher__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in matcher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatcherServiceStub(object):
    """🧠 Serwis
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMatch = channel.unary_unary(
                '/matcher.MatcherService/SendMatch',
                request_serializer=matcher__pb2.Transaction.SerializeToString,
                response_deserializer=matcher__pb2.MatchResult.FromString,
                _registered_method=True)


class MatcherServiceServicer(object):
    """🧠 Serwis
    """

    def SendMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMatch,
                    request_deserializer=matcher__pb2.Transaction.FromString,
                    response_serializer=matcher__pb2.MatchResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'matcher.MatcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('matcher.MatcherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatcherService(object):
    """🧠 Serwis
    """

    @staticmethod
    def SendMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/matcher.MatcherService/SendMatch',
            matcher__pb2.Transaction.SerializeToString,
            matcher__pb2.MatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
