# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matcher.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'matcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmatcher.proto\x12\x07matcher\"\xd3\x01\n\x07Invoice\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\x12\x13\n\x0bseller_name\x18\x03 \x01(\t\x12\x12\n\ntax_number\x18\x04 \x01(\t\x12\x18\n\x10total_net_amount\x18\x05 \x01(\x02\x12\x18\n\x10total_tax_amount\x18\x06 \x01(\x02\x12\x0e\n\x06\x61mount\x18\x07 \x01(\x02\x12\x10\n\x08\x63urrency\x18\x08 \x01(\t\x12\x12\n\nissue_date\x18\t \x01(\t\x12\x10\n\x08\x64ue_date\x18\n \x01(\t\"p\n\x0bTransaction\x12\x13\n\x0bsender_name\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x15\n\rtransfer_date\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"\x84\x01\n\x0bMatchResult\x12!\n\x07invoice\x18\x01 \x01(\x0b\x32\x10.matcher.Invoice\x12)\n\x0btransaction\x18\x02 \x01(\x0b\x32\x14.matcher.Transaction\x12\x12\n\nprediction\x18\x03 \x01(\x05\x12\x13\n\x0bprobability\x18\x04 \x01(\x02\x32I\n\x0eMatcherService\x12\x37\n\tSendMatch\x12\x14.matcher.Transaction\x1a\x14.matcher.MatchResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOICE']._serialized_start=27
  _globals['_INVOICE']._serialized_end=238
  _globals['_TRANSACTION']._serialized_start=240
  _globals['_TRANSACTION']._serialized_end=352
  _globals['_MATCHRESULT']._serialized_start=355
  _globals['_MATCHRESULT']._serialized_end=487
  _globals['_MATCHERSERVICE']._serialized_start=489
  _globals['_MATCHERSERVICE']._serialized_end=562
# @@protoc_insertion_point(module_scope)
